### ISSUE TITLE
Sorry you got the wrong idea

### ISSUE THREAD

**Issue by ghost** [SchdowNVIDIA/WhatCrates#9]
Do you have a tutorial on how to place a crate on the world? Because the tutorial you gave me I think you guys interpreted it wrong. I don't know how to activate the crates on the server.
![Screenshot_20190723-205712_Minecraft](https://user-images.githubusercontent.com/45384851/61714151-b712cc80-ad8c-11e9-89a5-31622063e81c.jpg)

**Comment by justin-eckenweber** [comment]
I didn't gave you any tutorial.
And WhatCrates is a plugin to make every block you want as a whatcrate so it doesn't need to be a chest. currently there are some issues if you're doing it with a chest but this will be fixed in 3.0.0. 2.0.0 is releasing very soon.

**Comment by justin-eckenweber** [comment]
Go into your whatcrates.yml and create/manage your crates there. in 1.X.X is no option to create them ingame.

**Comment by ghost** [comment]
Strange it is working now I just cleared the console but no announcement is
showing. I did /pa and wrote a message. Is it supposed to not show?

**Comment by ghost** [comment]
Sorry sir wrong send. I saw the whatcrates and see ut now how to manage it
thanks! I am so sorry for all that I have caused.

**Comment by justin-eckenweber** [comment]
It's okay. I'm closing this now.
